### ISSUE TITLE
Default to all namespaces for zarf tools monitor (k9s)

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1195]
**Is your feature request related to a problem? Please describe.**
Currently `zarf tools monitor` defaults to only showing the `zarf` namespace.  This shows people Zarf's state but is often not what people want to see (they want to see the state of additional packages installed on top as well).

**Describe the solution you'd like**
`zarf tools monitor` shows all namespaces by default

**Describe alternatives you've considered**
You could force a different default but showing them the full state of the system (while potentially minorly overwhelming) shows a clearer picture of the full state of things without needing to know to press `0`

**Additional context**
This is something I have seen cause confusion with a few users not knowing where their stuff was however would need review by @Madeline-UX.  Below is the current default:
![image](https://user-images.githubusercontent.com/3977569/212181664-2a658bf4-4fe2-4f36-a623-2df88784ebe8.png)

And this is what I would propose:
![image](https://user-images.githubusercontent.com/3977569/212181776-0d72ffd8-bff8-4001-af73-0f45b2874f26.png)

(note that there are pod statuses hidden from the user by default)

**Comment by RothAndrew** [comment]
This would be great! It's not at all the end of the world to just press "0" but it definitely has been a very small annoyance

**Comment by Madeline-UX** [comment]
User feedback and identified issues
- User did not see  their Kubernetes resources in K9 and were concerned that it may not have been deployed
- Filters are not very discoverable in k9 dash due to lack of labeling
- Package creators have expressed that they might have named the name-space something other than Zarf if this was not the default behavior
- Package creators have created resources with different name spaces and then wondered why they do not show up in k9 after deployment
