### ISSUE TITLE
Provide more clarity on "unable to push the git repo" warning message

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1211]
Zarf version v0.23.2

**Is your feature request related to a problem? Please describe.**
In the course of a `zarf package deploy` I receive several warning messages saying "Warning -- Unable to push the git repo", but zarf continues on deploying the package, and it eventually all comes up happy, which means to me that the git repo(s) were indeed actually pushed successfully. I suspect there is a retry that is happening, but it is not immediately obvious that that is the case.

**Describe the solution you'd like**
If this warning appears, it informs the user that it is retrying, and then lets the user know what the ultimate result was (failure or success)

**Additional context**
<img width="976" alt="image" src="https://user-images.githubusercontent.com/16000938/212982301-f19ae6e3-ca00-40ad-9464-a62aff8023b2.png">

**Comment by RothAndrew** [comment]
I do see that the next green line is showing the successful push of the same repo. So, perhaps the only thing needed here is to add the word "retrying..." to the end of the warning message.

**Comment by jbrewer3** [comment]
If you are able to reproduce maybe set log level to debug https://docs.zarf.dev/docs/user-guide/the-zarf-cli/cli-commands/zarf_package so that it will give more info as to why the Warning is being thrown.

**Comment by jeff-mccoy** [comment]
Correct @RothAndrew, we added a lot more retry logic throughout the deployment cycle, and I think this is actually not a great UX at this point. CC @Madeline-UX. I actually think just updating the spinner with "retrying" without throwing a warning is probably fine since it's something on larger image pushes that will happen from time to time. 

![Screenshot 2023-01-17 at 10 32 12 PM](https://user-images.githubusercontent.com/882485/213084795-aaabdcf8-a68b-49e4-830d-2ac9702eb5e1.png)

**Comment by Yash-C-330** [comment]
@jeff-mccoy I would like to contribute to this issue.
I would be changing the ' "Unable to push the git repo %s", basename' to "retrying".

**Comment by YrrepNoj** [comment]
For my 2cents, we have talked about being a little more descriptive in our warning messages in other places and I think that would make sense to continue on here.

I would ideally prefer:
`Unable to push the git repo {REPO_NAME} because of {ERROR_STRING}. Retrying the push.` if there are retries remaining
`Unable to push the git repo {REPO_NAME} because of {ERROR_STRING}.` if there are no retries remaining.

**Comment by jbrewer3** [comment]
If I am not mistaken the repo push will retry 3 times before failing?
![Screen Shot 2023-01-24 at 7 39 42 AM](https://user-images.githubusercontent.com/74952163/214309581-e581a5a4-4166-42d0-97ab-9eb66b0c0d18.png)

**Comment by Madeline-UX** [comment]
@YrrepNoj @jeff-mccoy Just seeing this. I agree with both of your statements that it should be more clear and we need to include that there tool is retrying the push. 

Ideally if there is no retries remaining - we should also make a recommendation for what they can do to try to fix the issue
