### ISSUE TITLE
Zarf integration with OSCAL to provide security control data with packages

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/zarf#1503]
### Is your feature request related to a problem? Please describe.
As a Zarf package developer, I would like to be able to include security control data along with my application(s) with [OSCAL](https://github.com/usnistgov/OSCAL). I would like to be able to easily discover this data and to know what controls my package satisfies/provides, and a description of how it satisfies them.

### Describe the solution you'd like
- A method to pull OSCAL artifacts into a Zarf package bundle at `zarf package create` time. Some way of visualizing this control data at package create time would be helpful.

- Once this package is built and pushed to an OCI registry, I would like to be able to fetch and visualize this OSCAL data in a user-friendly way natively with Zarf.

### Describe alternatives you've considered
- Use the `files` component to pull OSCAL artifacts into a Zarf package bundle at `zarf package create` time.
  - This gets the data into the package bundle, but doesn't give me a way to visualize or know what that data is without having to read through the files. Would like a more user-friendly way to visualize the data.
  
 - Currently, to fetch the OSCAL data, the workflow looks like:
 
 1. `zarf package pull` to fetch the package from a registry and save it locally
 2. `zarf tools archiver decompress` to extract the contents of the package
 3. `tar -xf` to extract the tarball of OSCAL artifacts
 4. View the raw OSCAL artifacts
 
 - A more optimal workflow could be:
 
 1. `zarf package inspect --oscal oci://my-registry.com/my-repo/zarf-package`
 
 This command could instruct Zarf to fetch the OSCAL data in the correct layer of the OCI artifact, and allow this data to be downloaded and/or visualized in a user-friendly way without needing to pull down the entire package and its contents.
 
 Would love to get thoughts and feedback.

**Comment by brandtkeller** [comment]
Current discussion:
- TODO: document the current state of Zarf and what the process looks like with Zarf functionality to-date. 
  - What can be done/how painful is the process/ can this be accomplished programmatically or are we missing some discoverability that prevents this.
  - Document the discoverability that would be beneficial to have.

- With the above established - we should look at the common building blocks that may have parallels to this process.
  - Evaluation for more generic "reporting/reports" that may be present in this space that identify package artifacts as associated with reports. 
  - IE VEX and OSCAL may benefit from a generic process that allows for identification as a "report" (or similar) artifact that `zarf package inspect` may be able to highlight. 

- Another datapoint is beginning to look at report context at the component layer instead of the package. More so relating to SBOM's here - but adding for additional context as we begin to think about the common building block more.

Let me know if this is too vague to allow for next steps. 

Note: some of this may already be done - capturing for posterity and future documentation.

**Comment by lucasrod16** [comment]
Closing because this is not a priority for the Zarf team
