### ISSUE TITLE
Improve package selection Web UI workflow

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1665]
## Is your feature request related to a problem? Please describe.
Our package selection workflow in the UI is a bit slow due to searching the entire home directory at one time.

## Describe the solution you'd like
Recommend the following changes:

### For 'init' package deployment
- [ ] in the selection window, only show init packages that exist in the three places that Zarf searches for them: 
  - Current Working Directory
  -  Zarf Binary Directory
  - Home `.zarf-cache` folder
  - If a user selects an init package that does not match the current zarf version - show an error message (this needs to exist in CLI too)

### Regular Package Deployment
For 'regular' packages -  the UX flow proceeds in two parts:
- [ ] Search # 1. 
     - Search and show packages located in the current working directory w/o subdirectories (matching the tab behavior on `zarf package deploy`)
    - If packages are found show in the table and add a expand search button to table that executes search # 2
    - If no packages are found - show no package found error message (gives the user option to cancel deployment or proceed to part # 2
- [ ] search part # 2
    - Search and show packages located in the entire home directory
    - Exclude trash 
    - Exclude hidden folders

- [ ] For both workflows, increase the height of the package selection table to show more packages at once

## Design File
https://www.figma.com/file/MUItIzpzLBLuIyt225Bwgl/Zarf-Web-Ui?type=design&node-id=1544%3A56348&t=JeB5xVvOb7lcP6ZB-1

**Comment by Madeline-UX** [comment]
@Racer159 - I updated this issue to discuss a new UX flow for searching for zarf packages. I changed a few things:
- Instead of hiding init packages that do not match current zarf version we should provide a warning on deployment that informs them of the risk. 
- Additionally if that behavior is in the web UI it probably should also be added to the CLI

**Comment by Racer159** [comment]
Not sure I agree with showing all init packages since that may be more dangerous then helpful - we pair them together because the init package contains the Zarf agent which can have breaking changes between versions and might break a cluster deployment in weird ways that would be hard to debug.

**Comment by Madeline-UX** [comment]
Is that a current behavior in the CLI as well?
What if the user wants to use a old version of the init package because that is what they have on their machine?
How can we guarantee a user got a new init package when they updated Zarf? (ex. disconnected user gets new zarf binary but not new init package and needs to destroy and reboot entire cluster and resources) Is this a failure?

**Comment by Madeline-UX** [comment]
Design is finalized and ready in Figma
