### ISSUE TITLE
authors package metadata type and format is ambiguous

### ISSUE THREAD

**Issue by timblaktu** [defenseunicorns/zarf#1810]
### Is your feature request related to a problem? Please describe.
Ambiguous naming and documentation of the type and format of the `authors` field in `zarf` package metadata leads users to incorrectly specify it, which then leads to ambiguous parsing errors (tracked in #1809).

The [documented type for `authors` package metadata](https://docs.zarf.dev/docs/create-a-zarf-package/zarf-schema#metadata) is correctly identified as `string`, however, in the same context it is ambiguously described as a "list". Supporting this ambiguity, there is no guidance on how the list of authors is to be formatted/specified. 

### Describe the solution you'd like

At its core, the issue here is that it is highly counter-intuitive that a plural yaml element be 
specified as a string instead of a list. 

If there is a reason why `authors` must be a string (other than general inertia to changing schema), the reason and its expected format should be properly documented.

Else, if there is no great reason why `authors` must remain a string, it should be changed to a standard yaml list.

### Describe alternatives you've considered

Spend more time RTMF.

**Comment by Noxsios** [comment]
@timblaktu The purpose of this `authors` metadata field is to be used as an annotation in the published package (source PR https://github.com/defenseunicorns/zarf/pull/1452).  The OCI spec states:

**org.opencontainers.image.authors**: contact details of the people or organization responsible for the image (freeform string)

Which is why I had it as a simple string for now, ofc this can easily be changed to a list and then marshaled back into a string during publishing.

Feel free to throw up a PR!
