### ISSUE TITLE
Distro-agnostic registry redirect

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#182]
As a user of Zarf's Utility Cluster mode, I need a way to automatically mutate image registries specified in kubernetes container specs to point at my utility cluster, so that I can utilize the utility cluster without having to change all of my configuration files to point at a different registry

Notes:

1. The way this is talked about being done right now is to create a new Zarf example that deploys Kyverno with the [replace-image-registry](https://kyverno.io/policies/other/replace_image_registry/replace_image_registry/) mutating webhook

**Comment by neoakris** [comment]
Additional Background Context:    
The reason Kyverno was suggested is because although containerd and cri-o offer registry mirroring functionality, they don't offer a consistent solution. A mutating webhook would result in a solution that's consistent regardless of the underlying implementation details (ex: cri-o vs containerd), and the mutating webhook is more push button to implement compared to the yak shaving exercise of figuring out a method of configuring cri-o / containerd's registry mirroring on every node.

**Comment by RothAndrew** [comment]
Talked about this for a bit today, mostly in relation to the native-apply stuff that is being worked on. If we end up making a "Zarf Agent" that runs in the cluster we may not need this, because that would handle the need here already.

/cc @jeff-mccoy

**Comment by jeff-mccoy** [comment]
Completed by #237
