### ISSUE TITLE
zarf tools registry pull - i/o time out error

### ISSUE THREAD

**Issue by Arsinic** [defenseunicorns/zarf#1929]
### Environment
Device and OS:  Mac book Pro local & eks gitlab runner
App version: v0.28.3
Kubernetes distro being used: eks on the runner
Other:

### Steps to reproduce
1. Using zarf version 0.28.3 attempt to `zarf tools registry pull ghcr.io/defenseunicorns/zarf/agent:v0.28.3 ./zarf` (the pulled image doesn't matter). The command always gives a timeout. 

### Expected result
The zarf command pulls images

### Actual Result
`Error: Get "<some non existant / unreachable cluster that exists in .kube/config": dial tcp <that.clusters.ip.addr>:443: i/o timeout`

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/defenseunicorns/zarf/assets/24624306/297b26fb-a43c-4d2c-bd8b-072fcf709dc6)

### Additional Context
Rolling back zarf version to v0.28.0 seemed to correct the issue, although that could be unrelated.

**Comment by Racer159** [comment]
This is because a `~/.kube/config` was found by Zarf but contains a cluster that cannot be reached or one that does not have Zarf state - v0.28.0 did not have the code that tries to lookup Zarf state which resolves this issue as well.  Pushed a PR though that will flag a warning instead of a hard error going forward.
