### ISSUE TITLE
Failed Building Dependencies in Gitea helm charts - 1.15.10

### ISSUE THREAD

**Issue by brandonw62** [defenseunicorns/zarf#1985]
### Environment
Device and OS: Gitlab CI  K8s runner - Alpine 3.18 Docker Image
App version: v28.4.0+
Kubernetes distro being used: N/A
Other:
When building our own Gitea package, the following error occurs during `zarf package create`.  Package creation is successful on Zarf v0.28.3 but fails with both v0.28.4 & v0.29.0
### Steps to reproduce
1.
`zarf package create .`
### Expected result
Package builds successfully
### Actual Result
Package fails to build
### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/defenseunicorns/zarf/assets/41562140/54c67987-34dc-4e8f-add8-e5cf610a2003)

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by Racer159** [comment]
For now if you run `helm repo add bitnami https://chart.bitnami.com/bitnami` does that resolve the issue as a workaround?

This is due to newer logic to build helm chart dependencies when they are encountered within charts to ensure things template correctly - initially we chose to copy what helm does which is to fail when repos don't exist but are looking at ways to refine it though (potentially making it warn only and/or being smarter about conditions).

Do you have a link to the gitea chart that you are using as well? `1.15.10-17` isn't a version of the upstream chart: https://gitea.com/gitea/helm-chart

**Comment by brandonw62** [comment]
I might be running into an issue with our proxy that is blocking me from adding the bitnami repo. The gitea helm charts should be v5.0.1. 

In this case, we've actually made a local copy of the helm charts:

![image](https://github.com/defenseunicorns/zarf/assets/41562140/d00d77c5-be81-469e-9ebf-20828444e429)

The version is labeled incorrectly - in this case, whomever modified these charts decided to use the application version of 1.15.10 instead of the helm chart version

**Comment by Racer159** [comment]
Ah if you have a custom modified chart you might be able to remove the dependencies as well if you don't need them / can't pull them.  Would be this section of the Chart.yaml: https://gitea.com/gitea/helm-chart/src/tag/v5.0.1/Chart.yaml#L32

It is looking for those 4 bitnami charts but if you don't have those values enabled under conditions you wouldn't need them - unfortunately Helm builds all dependencies OOB so following the conditions would mean writing our own logic for it (something we'll do but just have to think through).

**Comment by Racer159** [comment]
Also cc'ing @corang who has experienced similar things internally.
