### ISSUE TITLE
Use Iron Bank images for the PLG stack

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#214]
Currently we use PLG images from DockerHub. We need to get them from Iron Bank.

* `grafana/loki`
* `grafana/promtail`
* `grafana/grafana`
* `kiwigrid/k8s-sidecar`

**Comment by matt-strong** [comment]
@RothAndrew for this, https://github.com/defenseunicorns/zarf/issues/213 and https://github.com/defenseunicorns/zarf/issues/215 are we looking for getting/using the current versions we are using in DockerHub into IB?

**Comment by RothAndrew** [comment]
If IB has the images we need that will work for us. We should definitely make it a priority to get the latest versions of everything into IB but that doesn’t need to block this. The bigger priority is just that IB is the source for those images.

**Comment by jeff-mccoy** [comment]
We actually need to discuss this some more and make a plan, we have some housekeeping to do post-mega pr on how we manage arm vs amd and IB has no arm support at all because it's super lame. I'm less worried about pgl than gitea or registry2 for init beuxse those would be used with a Big Bang example--the only place someone would care about iron bank images. And between those two--we won't be able to use iron bank at all with the new injector stuff until iron bank uses an appropriate base images.  Iron bank takes an 9 msg image tarball and makes it over 100 mega by using the wrong base image.

**Comment by jeff-mccoy** [comment]
kicking this back to planned so we can sort through how we want to handle IB images for the init package.

**Comment by jeff-mccoy** [comment]
Closing IB stories for init package until we have a better plan, will consolidate into a new story.
