### ISSUE TITLE
Export version with zarf tools

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2142]
### Is your feature request related to a problem? Please describe.
As a user of the tools built into zarf I would like to know the version of the tool to be exported. 

### Describe the solution you'd like

- **Given** I run `zarf tools helm/kubectl/etc version`
- **When** I need to know the version for debugging purposes
- **Then** I get the version of the tool

I know this for sure doesn't work with helm.
Kubectl you get the server but not the client
```
Client Version: v0.0.0+zarfv0.31.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4+k3s
```

**Comment by Racer159** [comment]
To add this for kubectl this would be pulling the version into the LDFLAGS and building it correctly (this could be done with a command most likely similar to zarf-ui)

https://github.com/defenseunicorns/zarf/blob/main/Makefile#L32
https://github.com/defenseunicorns/zarf-ui/blob/main/Makefile#L30

For helm we would just need the `version` sub command to be vendored into Zarf under `src/cmd/tools/helm`:

https://github.com/defenseunicorns/zarf/tree/main/src/cmd/tools/helm
https://github.com/defenseunicorns/zarf/blob/main/src/cmd/tools/helm/root.go#L195
https://github.com/helm/helm/blob/main/cmd/helm/version.go

For crane this would be simply adding `craneCmd.NewCmdVersion()` to the registry cmd:

https://github.com/defenseunicorns/zarf/blob/main/src/cmd/tools/crane.go#L84C15-L84C23

For `k9s` this would be more ldflags: https://github.com/derailed/k9s/blob/master/Makefile#L29

For `syft` this is also more ldflags: https://github.com/anchore/syft/blob/dcd062cffb82c3e23f946a69591e9ed06dcf4d75/.goreleaser.yaml#L23

These could all be done individually if desired with `Relates to` this issue instead of `Fixes`

**Comment by eddiezane** [comment]
Instead of handling/vendoring each `version` command for the subtools directly, what do you think about having a `zarf tools version` command? We could pull the versions out of `go.mod` and bake them in via the linker.

**Comment by Noxsios** [comment]
@eddiezane `zarf version -o yaml | yq .dependencies | grep helm` xD

**Comment by eddiezane** [comment]
Neat! This is probably good to close with a PR to docs?

**Comment by Noxsios** [comment]
@eddiezane eh, I'm cool w/ that, but I leave it up to @AustinAbro321 as the issue opener to make that call.
