### ISSUE TITLE
Zarf Init with Signed OCI Package Cannot Be Validated

### ISSUE THREAD

**Issue by dgershman** [defenseunicorns/zarf#2248]
### Environment
Device and OS: AMD64 / Linux
App version: v0.32.1
Kubernetes distro being used: N/A
Other: N/A

### Steps to reproduce
1. Use a signed init package from an OCI-compliant registry.
2. Run `zarf package pull oci://some-repo/image:tag`
3. Run `zarf init --confirm` 

### Expected result

That you can use a signed init package.

### Actual Result

An error message appears saying to supply a key, except there is no `-k, --key` flag for `zarf init`.  

### Visual Proof (screenshots, videos, text, etc)

![Screenshot 2024-01-23 at 10 05 10 PM](https://github.com/defenseunicorns/zarf/assets/1850811/a6627bd7-c88f-4426-9dff-491095bc5487)

### Severity/Priority

Low

### Additional Context
We can work around this by validating the signature on `zarf package pull`, and then using the `--insecure` flag on `zarf init`.

You can also work around this by using `zarf package deploy oci://some-repo/image:tag -k`, as long as you don't need any of the flags specific to `zarf init`.

**Comment by Racer159** [comment]
Validated that this is a bug - it is because the init command is missing the `--key` flag.  Marked this as a good first issue as well since to fix it would simply require adding pkgConfig.PkgOpts.PublicKeyPath to the initFlags (likely under the "control how a deployment proceeds" section.

Relevant code:
https://github.com/defenseunicorns/zarf/blob/main/src/cmd/package.go#L335
https://github.com/defenseunicorns/zarf/blob/main/src/cmd/initialize.go#L215

**Comment by dgershman** [comment]
This issue also occurs with a non-OCI package.
