### ISSUE TITLE
Investigate what is necessary to create a GitLab 2FA example

### ISSUE THREAD

**Issue by Jesse-Arlington** [defenseunicorns/zarf#241]
Big Bang currently uses Keycloak, but this is not necessarily the best solution in all circumstances. Need to investigate GitLab as an alternative for 2FA. 

This came up in relation to a conversation and the issues encountered trying to deploy Keycloak.

Reference:
https://docs.gitlab.com/ee/integration/oauth_provider.html

**Comment by RothAndrew** [comment]
@Jesse-Arlington is this related to the "Software Factory" Zarf example?

**Comment by Jesse-Arlington** [comment]
> @Jesse-Arlington is this related to the "Software Factory" Zarf example?

Related. If we get it working it would be good to include inside of the Software Factory Example

**Comment by RothAndrew** [comment]
So I think Keycloak is still definitely the preferred solution since it is a "first-party" Big Bang integration. The limitation that we're seeing now is just in the context of this example that we're trying to put together by putting Keycloak in the same cluster as everything else. It is turning out to not be technically possible. In an operational scenario you would always run Keycloak in a different cluster, so this really only applies for the example.

The original description jumps into solutioning too quickly. We need to step back and figure out what the outcome is that we are looking for.

If I had to guess, the outcome is "we want to see some kind of SSO when using the 'Software Factory' Zarf example, so that it is a more complete example, compared to how it is now which is just a selection of tools that are running but don't integrate together."

Am I close?

**Comment by Jesse-Arlington** [comment]
@jeff-mccoy Rob doesn't seem to be in github. Can you make that happen and tag him to @RothAndrew's comment above?

**Comment by RothAndrew** [comment]
@unicornbunny182 is Rob. I asked him to add his name to his github account to make it easier. He's out sick right now so it'll happen later.

**Comment by jeff-mccoy** [comment]
Covid is no excuse to be such a slacker...

**Comment by dsracic** [comment]
> 

@RothAndrew - yup, your description is right.  Want a 2FA solution w/the Software Factory example...

**Comment by RothAndrew** [comment]
Closing in favor of #256
