### ISSUE TITLE
Update Software Factory example to include KeyCloak

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#249]
When using BigBang, KeyCloak is the preferred solution to SSO. The current iteration of the Software Factory example does not include KeyCloak because the example only stands up a single cluster while BigBang KeyCloak essentially requires the KeyCloak instance to be in its own cluster. 

After #237 gets merged this should be much simpler to implement.

**Comment by RothAndrew** [comment]
I suspect this issue conflicts with #241. Do people agree with that? Or is it feasible/worthwhile supporting both Keycloak and GitLab in some way?

If the two issues conflict, thoughts on which one is more desirable? (Keeping in mind that both still need to be refined more)

If they don't conflict, thoughts on which one is higher priority? (again keeping in mind that both still need more refinement)

Personally, I like Keycloak better right now, since it is more "BigBang-y" and would be less trailblazing, though possibly more technically challenging given the limitations we have already seen. Definitely not married to anything though.

/cc @dsracic @jeff-mccoy @unicornbunny182

**Comment by RothAndrew** [comment]
The plan right now is to do an engineering spike on GitLab being the SSO provider. Closing this issue for now. It can be resurrected later if needed.
