### ISSUE TITLE
[bug] Pod without labels will fail mutation

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/zarf#2517]
### Environment
Device and OS: AMD64 linux Server (ubuntu)
App version: v0.33.2
Kubernetes distro being used: Kind

### Steps to reproduce
1. Deploy zarf init package
2. Create a pod that contains no labels

### Expected result
Pod should be created and mutated by the zarf agent

### Actual Result
internal server error
```
Internal error occurred: replace operation does not apply: doc is missing path: /metadata/labels/zarf-agent: missing value
```

### Additional Context
Likely an edge case that does not occur often due to many clients adding default labels.

**Comment by lucasrod16** [comment]
I would like to better understand the use case that runs into this problem. Pods deployed by Zarf will always have a label on them, so I assume this problem only occurs when resources are deployed with `kubectl` into a Zarf cluster without the `zarf.dev/agent: ignore` label?

A pod with no labels that was not deployed by Zarf, even if mutated properly by the agent, would still fail to deploy due to other requirements that Zarf handles automatically:

- the image would have to manually be pushed to the Zarf registry before deployment
- `imagePullSecret` must exist in the same namespace and must be referenced in the pod spec to authenticate to pull the image from the Zarf registry

For these reasons, I would recommend adding the `zarf.dev/agent: ignore` label to the resources that are not deployed and managed by Zarf.

**Comment by brandtkeller** [comment]
This is very much handling for edge cases. The thread that spawned review revolved around the `local-path-provisioner` chart and how it uses a [helper pod](https://github.com/rancher/local-path-provisioner/blob/master/deploy/chart/local-path-provisioner/templates/configmap.yaml#L36) in a configmap as an "operator-like" execution for how it performs PVC creation. 

Easily worked-around by ensuring you change the configuration to include some arbitrary label. That does require forking and there may be a possibility that other operators orchestrate pods and do not set any labels by default? TBD - as I haven't seen this issue often but have seen it a handful of times over the last 2 years.

I'd argue low effort/low impact overall without more evidence that this is likely to continue to appear more often.

**Comment by joelcomp1** [comment]
@brandtkeller  do you have any more details on that work around? I am running into this right now on local path provisioner and updated the configmap to have a label but that isn't doing the trick. Is there anything else you had to do?

**Comment by brandtkeller** [comment]
@joelcomp1 provided you set some arbitrary label in the configmap this error should not appear. The attached PR - which was merged in May should prevent this from occurring - but you may have identified another edge-case for consideration. 

If you still are having issues and on the latest zarf version - we might want to have the team re-open this issue. 

Can you copy your configmap content here and I'll work to reproduce?

**Comment by joelcomp1** [comment]
Ah OK, it also is probably my old version of zarf I was running 0.32.6 in a full airgap environment so not easy to update at that point. I seemed to be able to resolve by doing a zarf destroy then a zarf init

**Comment by AustinAbro321** [comment]
@joelcomp1 You actually don't need to run zarf destroy, even zarf has already been installed on the cluster, re-running zarf init with a newer version will deploy the new agent.
