### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#26]
As a maintainer of Zarf I want visitors to have Issue Templates available so it is easy to provide a well formatted bug report or feature request

**Comment by ErrolFernandes** [comment]
Hey can I submit a PR for this?

**Comment by jeff-mccoy** [comment]
PRs certainly welcome. @RothAndrew do we have any repo restrictions right now from 3rd party contributions to do PRs?

**Comment by RothAndrew** [comment]
Nope. We should thinking about setting up a CLA though

**Comment by RothAndrew** [comment]
https://github.com/apps/cla-bot

**Comment by wadedesir** [comment]
@RothAndrew would love a review

# Summary
	Is this a bug? Is this a feature request? Why is this necessary? Go into detail.

# Steps to reproduce (optional)
	To replicate start by…

# Current Behavior

Please describe the behavior you are expecting

# Expected Behavior

Please describe the behavior you are expecting

# Context
- Zarf Version
- OS
- Etc

## Logs / Error messages
	

## Additional details

**Comment by RothAndrew** [comment]
@wadedesir can you submit as a PR rather than a comment?
