### ISSUE TITLE
Issue with Package publish to Gitlab Registry

### ISSUE THREAD

**Issue by cbrech** [defenseunicorns/zarf#2605]
### Environment
Device and OS: Mac OS, Linux, and Linux via WSL (tried all 3)
App version: Zarf v0.34.0
Kubernetes distro being used: K3D
Other:

### Steps to reproduce
1. Run zarf package create
2. Run zarf package deploy (check that packages deploys locally well, which it does)
3. Run zarf package publish xxxxx.tar.zst oci://myregistry.url.com/suburl (zarf says successfully published)
4. Login to gitlab instance and view container registry. Tag shows up but next to tag is a yellow triangle icon with the warning "Invalid Tag: missing manifest digest"
5. Try running zarf package deploy  oci://myregistry.url.com/suburl/package:0.0.1 and get error ""Failed to deploy package: unable to load the package: sha256:zzzz: not found: no matching manifest was found in the manifest list"

### Expected result
Zarf package publishes to registry, registry recognizes it and processes it, other computers can pull package from registry and deploy.
### Actual Result
Gitlab registry sees the tag but no other details like architecture or package size. Says 0B for size. Git errors such as file not found when trying to include in a UDS bundle and no matching manifest when deploying.

### Visual Proof (screenshots, videos, text, etc)
<img width="262" alt="Screenshot 2024-06-10 at 1 34 00 PM" src="https://github.com/defenseunicorns/zarf/assets/55962053/9aeb9646-fe30-4f67-b631-da100a4e5431">

### Additional Context
I've also noticed that sometimes the upload takes a normal amount of time for the size of the package and other times (even on a brand new package) it uploads over a gig instantly. 

Thanks!

**Comment by lucasrod16** [comment]
@cbrech Thanks for opening this issue!

I believe there are two separate issues here.

The first issue is a bug in GitLab that does not handle OCI image indexes correctly, which is the format used for Zarf packages.

See these GitLab issues for more details:
 - [Container Registry - multi arch docker images no longer available from Gitlab 15.8.x : Invalid tag: missing manifest digest](https://gitlab.com/gitlab-org/gitlab/-/issues/393202)
 - [Show supported platform(s) of multi-architecture container registry images in the UI](https://gitlab.com/gitlab-org/gitlab/-/issues/369852)
 - [Display additional details for container registry tags that point to manifest lists/indexes](https://gitlab.com/gitlab-org/gitlab/-/issues/408873)
 - [Improve container registry multi-architecture images UX](https://gitlab.com/groups/gitlab-org/-/epics/11952)
 
 Here is what a Zarf package's OCI image index looks like for an `arm64` package:
 
 ```json
 {
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:348322b5ef9d6ee492488f5b0e9410bda5f06ac23df9b48ff246c4db7b7f32a9",
      "size": 2872,
      "platform": {
        "architecture": "arm64",
        "os": "multi"
      }
    }
  ]
}
 ```
 
The second issue is likely due to mismatched CPU architectures. The error `no matching manifest was found in the manifest list` happens because the package architecture does not match your deployment machine's architecture. For example, deploying an `arm64` package on an `amd64` machine without using -`-architecture=arm64` will cause this error.

Ensure the package's architecture matches the target cluster's architecture. If deploying from a machine with a different architecture than the package, use the `--architecture flag` to specify the correct package architecture during deployment.



You can check a package's architecture with:

```shell
zarf package inspect oci://myregistry.url.com/suburl:tag
```
And check the `.metadata.architecture` field

Let us know if this resolves your issue!

**Comment by cbrech** [comment]
Thanks for the quick reply. 

Is it your understanding that the Gitlab container registry handles OCI images correctly but the UI does not or that its registry does not handle OCI packages properly?

Have y'all seen any best practices for using a gitlab registry with Zarf? Should we be naming each package with its architecture?

**Comment by lucasrod16** [comment]
> Is it your understanding that the Gitlab container registry handles OCI images correctly but the UI does not or that its registry does not handle OCI packages properly?

Yes that is my understanding. The GitLab container registry API accepts the upload successfully from `zarf package publish` and seemingly stores Zarf packages correctly since they can be pulled and deployed from there. The UI does not handle the data correctly though and displays the slightly confusing and misleading warning `Invalid tag: missing manifest digest`

> Have y'all seen any best practices for using a gitlab registry with Zarf? Should we be naming each package with its architecture?

I am not aware of any specific best practices for using GitLab container registry with Zarf. We have had this issue brought up with the GitLab container registry UI not displaying Zarf packages correctly, but as seen in the linked issues above, that is not specific to Zarf.

I would not recommend naming each package with its architecture. That may be a tempting thing to do to work around the GitLab bug, but it isn't a pattern I would recommend because the standard place to store and retrieve architecture metadata for OCI artifacts is the OCI image index, which is where it is currently stored for Zarf packages.
