### ISSUE TITLE
`Zarf connect` command doesn't work in Vagrant

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#261]
Zarf binds to 127.0.0.1 when doing the `zarf connect` which conflicts with the networking of the Vagrant box making the traffic not actually accessible outside of the Vagrant vm.

`zarf connect` is essentially just a wrapper around `kubectl port-forward`. One solution is to run `kubectl port-forward --address 0.0.0.0 {EVERYTHING_ELSE}`.  

This issue is mainly here to acknowledge the issue and give us a place to determine if we want to:
1. Add a flag to `zarf connect` to set the address location
2. Not worry about this since the multi-distro-support PR means we can eventually migrate our examples to docker w/ KIND leading to even simpler example deployments.

**Comment by jeff-mccoy** [comment]
Only minor note is it's not actually a wrapper, it's a native go implementation of that same kubectl function.  That matters because it means zarf doesn't require kubectl exist for this to work.

**Comment by RothAndrew** [comment]
IMO, assuming it doesn't break anything, I'd like to see `zarf connect` just internally do the equivalent to `--address 0.0.0.0` without needing a flag. That's assuming nothing breaks somewhere else if that is the case. If other things do break then yeah we'd need a flag added to `zarf connect`

**Comment by jeff-mccoy** [comment]
I think the issue is it's actually a  security risk.  You're essentially publicly exposing your internal k8s components unencrypted if you bind to anything but localhost. And this currently is an edge case so probably shouldn't be the default behavior, we should always aim to reduce exposure as much as possible.  I think the real compromise is if you need something exposed on 0.0.0.0, then you probably should add an ingress or at least nodeport as those are better suited to hosting external traffic. Alternatively we could add a flag along the lines of "--insecure-public-bind" or something to bind to 0.0.0.0.

**Comment by RothAndrew** [comment]
Gotcha, yeah I wasn't sure whether there were any security implications.

In that case, maybe just stick with having an `--address` flag to mimic the established convention from `kubectl port-forward`?

**Comment by jeff-mccoy** [comment]
Yeah that's fair too, I just worry some of zarfs target users would never run such a command or know what to do so might not appreciate the security implications. Either way definitely worth talking about some more.

**Comment by anoncam** [comment]
@thejohnny do you have any good Vagrant POCs on the Hashicorp side?

**Comment by jeff-mccoy** [comment]
I think we'd be better off just removing vagrant at this point as all the local distros test Zarf just fine without a VM

**Comment by jeff-mccoy** [comment]
The docs no longer refer to Vagrant so this should no longer be a major concern.
