### ISSUE TITLE
Import OCI Composable Package fails

### ISSUE THREAD

**Issue by kcighon** [defenseunicorns/zarf#2617]
### Environment
Device and OS: Ubuntu 22.04
App version: v0.34.0
Kubernetes distro being used: v1.29.4-k3s1
Other:

### Steps to reproduce
- Create a package and push to an OCI registry.
- use "import" in zarf.yaml manifest with url pointing to your oci:// url to above package
```yaml
...
  import:
      url: oci://myregistryurl/oci-dev/zarf-package/flux:2.2.3
```

### Expected result
- Above image included as a composable package
### Actual Result
- Following error observed:
```bash
published skeleton package for "oci://myregistryurl/oci-dev/zarf-package/flux:2.2.3" does not exist: sha256:cad2402e00xxxxxxx: not found: no matching manifest was found in the manifest list
```
- Tested on harbor and artifactory OCI Repos
### Additional Observations
- import works with `path` parameter direct to package file.
### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by lucasrod16** [comment]
Hi @kcighon,

Thanks for opening this issue. The error occurs because you're trying to import components directly from a published Zarf package. To fix this, publish a "skeleton" version of the package to your OCI registry first.

Run the following command:

```shell
zarf package publish path/containing/package/definition oci://your-registry.com
```

For more details, see the [documentation](https://docs.zarf.dev/ref/components/#component-imports).

Let us know if this helps!

**Comment by kcighon** [comment]
Many thanks - that works great!

As a matter of interest, is it possible to use a ZARF_PKG_TMPL... variable as the OCI import.url?

Having the variable in our zarf-config.yaml would make more sense than using anchors (https://github.com/defenseunicorns/zarf/issues/2183).
