### ISSUE TITLE
Use Testify's `require.NoError` instead of `assert.NoError` in tests

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#405]
Using `require.NoError` in cases where all subsequent assertions would be guaranteed to fail will allow the tests to fail faster. If we limit the change to just areas where all subsequent assertions will be guaranteed to fail we can fail fast when we are able to and get more context on failed tests when that context is available.

---

Original description:

Using `require.NoError` instead of `assert.NoError` will allow the tests to fail faster. `assert.NoError` allows the test to continue, only failing at the very end. `require.NoError` fails immediately.

**Comment by YrrepNoj** [comment]
If the result we are checking for has catastrophic impact on the following 'assertions' in the test i.e. everything afterwards is going to fail no matter what, then I agree we should be using `require` instead of `assert`. Otherwise, I would rather us use `assert`. Seeing what other conditions is failing could offer deeper clues as to what is actually wrong. I would rather have the test take a couple extra seconds/minutes and have more information to work off.

If we were doing unit tests then using `require.NoError` makes a lot of sense because usually you're testing a small enough unit that a single error means you already know the outcome of that test case. But since we're using larger e2e tests that are trying to validate a wider range of functionality I think there's still value in letting the tester continue.

**Comment by RothAndrew** [comment]
Works for me. I'll update the description to specify only changing ones that would always fail if the assertion(s) that came before it fail

**Comment by RobertKwiatkowski** [comment]
I can work on it however I'm a little bit confused. Should the line like here: https://github.com/defenseunicorns/zarf/blob/master/test/e2e/e2e_composability_test.go#L32 be changed to require? Since if you fail the get request you won't be able to do the rest of actions?

**Comment by RothAndrew** [comment]
I think yes, that would be a good example of one that we would want to switch to require, as well as line 36 since without a body it will be guaranteed to always fail

**Comment by RobertKwiatkowski** [comment]
I just reviewed rest of the test files and to be honest I see no more lines to replace the assert with require. Usually when the assert is used it's at the end of test or there is bunch of calls like: check commits, checks tags or check Gitea, check Grafana, establish port forward.

Since those are definitely e2e tests I have to agree with @YrrepNoj it's better to wait few more seconds/minutes and get bigger picture about the failure.

Anyway, if you want I can create PR just with changes in the file mentioned above, let me know.

**Comment by RothAndrew** [comment]
Sounds great, thanks!
