### ISSUE TITLE
Simplify Kubernetes cluster instantiation in tests

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#406]
Currently, the test suite utilizes the Golang packages for K3d and KinD to create clusters internally. This is causing issues as I attempt to write a new E2E test that tests functionality with non-standard `KUBECONFIG` environment variables, since it does a complicated series of checks, validations, and logic. It currently does this:

1. Determine if a cluster is already running, and if it is, use it instead of creating one
2. If a cluster isn't running, create one, using a hard-coded `KUBECONFIG` file (`~/.kube/config`)

I believe it would be far simpler and more scalable to abstract that out into the environment. I propose:

1. Expect (and validate) a cluster to be running already, unless explicitly told to instantiate the built-in K3s cluster

It would add a bit more code to the GitHub Action yaml scripts, since the Action would now need to handle creating a cluster and destroying it after the tests finish, but would make the Golang code in the `test/e2e` folder much simpler and easier to maintain.

**Comment by YrrepNoj** [comment]
Is the issue that the hard-coded place it was writing to was a commonly used place? Would writing it somewhere else be a workaround?

Having the test standup the cluster helps ensure the cluster is in the same state each time, otherwise tests might fail/pass because of already existing resources. Obviously we allow for existing clusters to be a thing so that can still happen currently, but  if we make it a requirement when testing locally then it's something that we'll start run into more often.

I also found it useful when doing dev work to either:
1. Make small changes to the project and run `TESTDISTRO=kind go test ./... -run TestThatsFailing` without having to worry about manually destroy and recreate a kind cluster to get a clean testing slate
2. Run the single `make test-e2e` and walk away and take a break while the tests ran against all the distros with some result ready for me when I came back


These are things I could live without, but would rather not lose it if it's possible.

**Comment by RothAndrew** [comment]
It was failing in the same way as the `getRestConfig()` function in `common.go` was, due to my `KUBECONFIG` env var having multiple files in it, which IMO we should absolutely support since `kubectl` does. As I tried to work through fixing it I became lost, trying to work through how I would support that functionality, while still doing the internal clusters using the KinD and K3d libraries. After a couple of hours of head-bashing I came to the conclusion that I wanted to propose a different solution.

Here are some alternative commands you could run to get the same functionality as you had:

1. `kind create cluster && go test ./... -run TestThatsFailing && kind delete cluster`
2. `kind create cluster && make test-e2e && k3d cluster create && make test-e2e && k3d cluster delete`

Though, for #2 it would be quite a bit faster to just push your WIP code and let the pipeline run it.

**Comment by RothAndrew** [comment]
> Having the test standup the cluster helps ensure the cluster is in the same state each time, otherwise tests might fail/pass because of already existing resources.

That is definitely a valid concern, though IMO the benefit outweighs the risks.

**Comment by RothAndrew** [comment]
Also the `k3s` set of tests still always destroy and recreate due to the nature of `zarf init` and `zarf destroy`

**Comment by YrrepNoj** [comment]
I agree we should support multiple files in the KUBECONFIG. What if we leaned into that even more and 
1. have the tests standup the cluster
2. write the config to a test-zarf specific file in ~/.kube/ (so we don't overwrite a real file like we are now)
4. then change the `current-context` to the cluster the test created? 

That's a good point about `zarf destroy` but that's also something that can be turned into its own test.

**Comment by RothAndrew** [comment]
IMO the much simpler code outweighs the value in creating and destroying the cluster each time internally, particularly since the K3s set of tests still do that.

**Comment by RothAndrew** [comment]
Updated PR description after offline discussion with @YrrepNoj, check #407 for latest design
