### ISSUE TITLE
Add language file support for Zarf

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#631]
## Current State ##

There is different language formats used throughout the application. The inconsistency and lack of pattern makes it difficult for new contributed to know how to write error messages. 

## Desired Solution ##

For improving the UX experience, the design is interested in reviewing and offering feedback on language and messaging within the application. This would also help support adding languages in the future as well.

**Comment by Racer159** [comment]
Once we build in support to get our strings from a central source we could also look into a project like https://www.transifex.com/. (found them from trawling around the Neverball source https://github.com/Neverball)

**Comment by Racer159** [comment]
Linking this here since it is somewhat related (but could be fixed before this story) https://github.com/defenseunicorns/zarf/issues/923

**Comment by Racer159** [comment]
Also: https://github.com/defenseunicorns/zarf/issues/926

**Comment by UncleGedd** [comment]
(copy/pasting from Slack) I'd like to see more helpful error messages during package creation. I got this one when attempting to build the Big Bang package. Turns out I wasn't logged into registry1. It didn't take long to figure out, but in th
![Screen Shot 2022-11-08 at 4 42 38 PM](https://user-images.githubusercontent.com/42304551/200852231-f7293ced-ebe0-4df7-87fd-eb3f065910d2.png)
e spirit of "don't make me think", it'd be nice to have an error msg that indicated so
