### ISSUE TITLE
Creating a Zarf package fails on zarf-injector step

### ISSUE THREAD

**Issue by NunoSav** [defenseunicorns/zarf#708]
### Environment
Device and OS: macOS 12.5.1
App version:  v0.21.2
Kubernetes distro being used: k3s
Other:

### Steps to reproduce
1. Follow steps at https://docs.zarf.dev/docs/walkthroughs/creating-a-zarf-package

### Expected result
Zarf package is created

### Actual Result
```
  ✔  defenseunicorns/zarf-injector:amd64-v0.20.0-31-g4e902fc cosign verified: CLAIMS. TRANSPARENCY LOG (BUNDLED). PUBLIC KEY.
     ERROR:  Unable to copy build/zarf-registry-amd64
```

### Visual Proof (screenshots, videos, text, etc)
<img width="914" alt="Screenshot 2022-08-30 at 09 22 08" src="https://user-images.githubusercontent.com/26490343/187387468-be5d0778-e7d7-492e-8300-53ba3eaa70b7.png">

**Comment by jeff-mccoy** [comment]
Yeah that's a bit confusing, you don't actually have to build the init package as they are published already on the GitHub release.  If you're just testing zarf online following https://zarf.dev/install, the init package will be downloaded on "zarf init". 

The actual error your seeing is because there's a prestep for init you have to do to build the secondary go binary.  You would use "make init-package ARCH=" where arch is arm64 or amd64. This would create the prerequisite binary for you.

**Comment by YrrepNoj** [comment]
> @YrrepNoj what do you think about defining the go build in a prepare script now that we have the capability in zarf?

I'm fine with that. 

I know we stopped doing released versions of the injector because they don't update at the same cadence but I would also be happy with making the injector logic it's own project that way we can release the binaries for that instead of hiding the build of them within a Make target.
