### ISSUE TITLE
Make "Saving log file..." on every command less annoying

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#776]
Currently Zarf writes `Saving log file to <path/to/logfile>` to stderr on every command run, which is annoying.

Ideas:

* Suppress the "saving log file" message unless the log level is elevated (e.g. `-l debug`)
* Output the location of the log file if the exit code is nonzero, otherwise don't mention it (unless log level is elevated as previously mentioned)
* ??

<img width="548" alt="image (1)" src="https://user-images.githubusercontent.com/16000938/192048436-c095fc5d-63e2-4d54-8deb-6e1f747f1f80.png">

**Comment by jeff-mccoy** [comment]
1st option won't work as that defeats the purpose of this logging to begin with. We need a way to capture logging on failure / crashing as well as for user support when troubleshooting.  

#2 might work, though again for user support where it's not a crash, that would not be helpful. 

Likely best option is to remove where it doesn't make sense (like on help commands / vendored code) and maybe a disable log file global flag.

**Comment by RothAndrew** [comment]
Should Zarf write a log file on every command run? Seems excessive, vs the ability to output the log to a file as a user choice.

**Comment by YrrepNoj** [comment]
Perhaps we could find a way to do a lifecycle hook style cleanup of the log. If no error has been caught, we can cleanup the log file.

I very much see the benefit of having a log output on failure, I feel like that is super useful for an end-user who wasn't expecting an error in the first place (vs having to re-run the failed execution again and remembering to pipe output to a file the second time)

**Comment by YrrepNoj** [comment]
That way we can also only print the warning log of the file location only if the log file is going to remain

**Comment by jeff-mccoy** [comment]
I disagree @RothAndrew. You are coming from a perspective of a k8s expert + power user of zarf and other CLIs.  

Zarf needs a way to show simple output, but also capture detailed messaging for troubleshooting. I would much rather have a power user have to add a flag to suppress something they find excessive than tell lower skilled users to also add a flag if they want support. More importantly, the flag could later just be an env variable or config file if we user viper. 

That being said, I also find the log line annoying (and I wrote it), but it was a good first effort to provide the functionality. Now we can iterate on it, but just removing the capability is not an option.

**Comment by jeff-mccoy** [comment]
I did look at using log systems instead, but that was messy cross-platform. I also looked at a single log file so we wouldn't have to log this out each time, but that can have write-lock issues and eventually lead for the need for log rotation.  Happy to chat about ways to improve this and make it less annoying...but this level a logging as a default is a must for a large portion of our users.

**Comment by RothAndrew** [comment]
Cool cool cool. Can you walk me through the feedback you got that led you to the understanding that the users that want this want it for every command run, even successful ones? I'd love to see that. I really do want to get a better understanding of that user persona.

cc @Madeline-UX

**Comment by jeff-mccoy** [comment]
Feedback wasn't "I want to see a log output every time", but as @YrrepNoj said we encounter many times where users are troubleshooting issues and we have to ask them to rerun with the debug flag on and send us output. Like I said, first iteration that we will likely improve over time.

I'm curious what your root concern is, is it disk space, a stderr log that won't be captured in piping, or something else?

**Comment by RothAndrew** [comment]
no other concerns atm other than just that it's annoying that it appears every time, though if I were to hazard a guess at what the future might hold I can envision complaints such as disk space filling up, or needing the ability to direct the logs to some other directory based on the user's mount layout (tiny root volume, bigger volume somewhere else)

**Comment by Racer159** [comment]
@jeff-mccoy @YrrepNoj @RothAndrew @Madeline-UX to make this "smarter" we could only always show the log file directory as part of the debug logs instead of the normal output and when Zarf fails have the log file location as part of the failure text (since we already have a common error-handling message component).

**Comment by Madeline-UX** [comment]
@Racer159 what would the user flow for this look like? What happens when user gets unexpected result that is not technically an error and needs to pass back logs to resolve?

Any solution must be discoverable, and clear for our end user persona Ashton (Jr IT Sys admin) - who likely has minimal CLI experience. Additionally, I would like to assist with the CLI design for this one (colors, language, etc) and make sure we do some usability testing around this too. 

@RothAndrew The user persona Zarf is targeting is  Ashton a "Jr Sys Admin." here is the user persona https://userbit.com/external/88iAMwjH1tCrv1ZerWpt/persona/sPVhRaarYHwA4Yf7pXN7|

**Proposed Desired Outcome(s):**
Ashton will be able to discover and successfully export log files anytime that the system behaves in an unexpected manner.

**Usability testing metric:8**
(any solution needs to pass this standard)
The Jr Sys Admin will be able to find the log file and export it with a 90% accuracy on the first attempt. (Looking through docs or reaching back = failure)

Solutions should meet team design standards from issue #583

**Comment by RothAndrew** [comment]
@Madeline-UX 
![image](https://user-images.githubusercontent.com/16000938/192369021-f05d81b0-85c1-4988-8ad2-91c5ec0e7c11.png)

**Comment by Madeline-UX** [comment]
@RothAndrew - Link is updated.

**Comment by JasonvanBrackel** [comment]
I think @jeff-mccoy is right, and I'll go one further.  I think the message at the front is necessary, and there should be a reiteration at the end that it was saved with the path.

There are lots of observability cases where one might look at a log besides a non-zero exit, and for this to be discoverable on a CLI, it has to be a little noisy.

I bristled at this when I first saw it because I've worked extensively with CLI and K8s.  It's out of the "usual".   But I'm not the target audience for the tool.  Remember our deployment environments are not "usual" and while this tool will be able to package and deploy for any environment, that any includes places like a SCIF being managed by a non-CLI, non-K8s expert.

**Comment by RothAndrew** [comment]
Works for me, though it is worth reminding that there are multiple target audiences for the tool. In this specific case functionality is needed that helps one target audience to the detriment of another.

Thank you for helping me understand the other target audience better, I can live with the minor annoyance if it means helping Ashton be more successful in his use of Zarf 😄

**Comment by Madeline-UX** [comment]
@RothAndrew There is going to be a balance there for sure. This feedback is still insightful and I marking this as something to focus on in usability testing.

**Comment by jeff-mccoy** [comment]
#781 will also allow couple things that should eleminate this issue for some users:

1. The `--no-log-file` flag will prevent Zarf from creating log files (or announcing it)
2. You will be able to set a config file that Zarf will auto-read in your home directory, CWD or by env variable to disable this feature
![Screen Shot 2022-09-26 at 3 56 36 PM](https://user-images.githubusercontent.com/882485/192378837-65e9c637-082d-4041-98f7-0fe05ea7ac10.png)

3. You will also be able to just set the env variable `ZARF_NO_LOG_FILE=true` to disable it

**Comment by jeff-mccoy** [comment]
So in @RothAndrew's case, you could just update your .env if you use those or your shell init scripts to set this env variable at all times.
