### ISSUE TITLE
UI runs same command to search for cluster twice

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#820]
### Environment
Device and OS: macOS
App version: Zarf - master branch
Kubernetes distro being used: Kind
Other: Zarf dev UI

### Steps to reproduce
1. When first starting Zarf UI on a new cluster. Click initialize now button 
2. then the app begins to reroute to deployment wizard but then goes back to first screen
3. Reruns the search for cluster again and requires user to have to re-click the same initialize button

### Expected result

When user clicks the initialize button it goes to the initialize wizard

### Actual Result

Currently the user has to click the button twice

### Visual Proof (screenshots, videos, text, etc)

https://user-images.githubusercontent.com/92826525/193349418-8d9a70c2-cfd5-42cf-b231-99d629a3d179.mov

### Severity/Priority
High - must be fixed before releasing publically - interrupts user experience and results in users feeling insecure because they thought they just clicked the initialize button then they have to do it again (validated in user testing)

### Additional Context
Not sure if this is happening on other builds or with other K8 distros

**Comment by Noxsios** [comment]
This bug only occurs during `make dev` due to Vite's hot-module reloading of components.  The following lines are the source of this bug,

```text
[ui] 2:26:00 PM [vite] ✨ new dependencies optimized: prismjs/components/prism-yaml, prismjs, yaml
[ui] 2:26:00 PM [vite] ✨ optimized dependencies changed. reloading
```

Such behavior is not showcased in the built binary, when run w/ `zarf internal ui -l=trace`

I suspect that during dev, the HMR takes place before the page redirect --> `initialize/configure`, and since the URL bar is a lie (due to SPA mode), it appears to route to `initialize/configure` when in fact `/` page is being refreshed.

**Comment by jeff-mccoy** [comment]
Concur, closing as a dev-only concern since we now cut RCs regularly
