### ISSUE TITLE
Archiver fails if files are already present

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf#858]
**Is your feature request related to a problem? Please describe.**
I'm working on building a Zarf package to deploy some terraform ([see package here](https://github.com/defenseunicorns/zarf/tree/adds-terraform-example/examples/terraform)), and I ran into an issue with the archiver. If I deploy the aforementioned package, everything works swimmingly, but if I deploy again (say I'm adding another TF provider), then it fails with the error message below. Tracing it back to the codebase and docs, it looks like the `mholt/archiver` will fail to extract if the files already exist, unless you set an option called `OverwriteExisting` in the archiver.

I know it's possible to simply delete the files that are making the archiver fail, but in the case of TF, it feels weird to have to delete the plugins directory. This is especially true if I want to run terraform commands in between updating the TF Zarf package.

**Describe the solution you'd like**
I'd like a flag on the `zarf tools archiver decompress ...` command that would allow the archiver to overwrite files if they already exist

**Additional context**
Error message after running `zarf package deploy <myPackage>` twice
<img width="1706" alt="Screen Shot 2022-10-06 at 1 43 58 PM" src="https://user-images.githubusercontent.com/42304551/194402258-2858a021-0890-49ee-aefd-1a800509b2c1.png">

**Comment by JasonvanBrackel** [comment]
I like that flag.  It's a good idea.   Can you also improve the flow so it checks for the file and the error message mentions the file already exists, and that the overwrite flag can override with a fixed command line?

**Comment by UncleGedd** [comment]
Yep, can do!

**Comment by UncleGedd** [comment]
After a few days of testing, I believe overwriting existing files during decompression may not be possible with our current version of `mholt/archiver`. Basically, we can set the `OverwriteExisting` property on various types of archives, but this config is not respected by the `archiver.Unarchive` function. This is known issue in v3 of `mholt/archiver`: https://github.com/mholt/archiver/issues/264

I would normally just upgrade the package and go on with my life but v4 of `mholt/archiver` is in [alpha](https://github.com/mholt/archiver/releases). So, I'd like to get the Zarf team's perspective before I update (personally I think it's fine as long as the tests pass 🤷 )

**Comment by jeff-mccoy** [comment]
We do have pretty good E2E, but Archiver has a lot of tests missing in that version. I actually looked at it early this year when he rewrote most of it and I think there are a lot of positive changes--but I'm not super keen on switching something so core to what we do to an alpha library.  Maybe we can take a look again at the root cause as this is an edge case.  Couple ideas:

1. Use a binary vs archive for the file (zarf already zstd compresses everything)
2. Add a script to remove the file first if it exists (or ignore errors)

More broadly, I'd love to chat when you have time on the terraform stuff, as soon as I get done with #934 I'm going to start working on a POC modular/extension/plugin/🦄 system for Zarf that will make adding terraform/pulumi/ansible/etc very fluid (I think).  More to come on that.

**Comment by UncleGedd** [comment]
Agreed on this being an edge case especially if we have future plans for more native Terraform support. Also agreed that it's risky to update a core package to an alpha version. I think users can just go with the second option for now and write a `before` script to blow away files if they exist
