### ISSUE TITLE
Unable to Deploy Doom Game into Existing EKS Cluster - amd64 mismatch

### ISSUE THREAD

**Issue by vennemp** [defenseunicorns/zarf#955]
### Environment
Device and OS: MBP M1Pro 12.6
App version: v0.22.2
Kubernetes distro being used: eks
Other:

### Steps to reproduce
1. Cloned repo.
2. Kubectl works fine with the cluster.
3. zarf init returns
ERROR:  The current Zarf package architecture arm64 does not match the cluster architecture amd64

**Comment by jeff-mccoy** [comment]
The way zarf works by default is it assumes the cluster (EKS in this case) and the CLI binary are the same architecture. Because you're connecting to a different arch ARM -> AMD, you'll need to specify a flag to tell zarf to use a different architecture for the packages:   https://docs.zarf.dev/docs/user-guide/the-zarf-cli/cli-commands/zarf#options.

E.g.:
`zarf init -a=amd64`

**Comment by vennemp** [comment]
thank you!

**Comment by Racer159** [comment]
Added a few labels to mark this as an error message to look at during https://github.com/defenseunicorns/zarf/issues/631

**Comment by mjnagel** [comment]
> The way zarf works by default is it assumes the cluster (EKS in this case) and the CLI binary are the same architecture. Because you're connecting to a different arch ARM -> AMD, you'll need to specify a flag to tell zarf to use a different architecture for the packages: https://docs.zarf.dev/docs/user-guide/the-zarf-cli/cli-commands/zarf#options.

@jeff-mccoy would there be value in adding a prompt to pull an init package with architecture matching the cluster? I'm thinking this could fit in well where the current prompt for downloading an init package is:
```
It seems the init package could not be found locally, but can be downloaded from
https://github.com/defenseunicorns/zarf/releases/download/x/x.tar.zst

Note: This will require an internet connection.
? Do you want to download this init package? (y/N) 
```
Could either before or after this check for a cluster connection and provide a similar prompt if an init package matching that architecture cannot be found locally. I think this would be beneficial since currently the error message for mismatched architecture doesn't pop up until further along in the process.

**Comment by Noxsios** [comment]
I think this can safely be closed as completed. The mismatched arch error messaging is pretty good now due to #1495 and other UX improvements.
