### ISSUE TITLE
Ability to specify package version as part of the filename

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#970]
**Is your feature request related to a problem? Please describe.**
When I build a zarf package, the package's version is not included as part of its filename, even if I specify a value for `metadata.version` in the zarf.yaml file. This makes it more difficult to track which version of the package is being used on deployment, since they all are named the same way.

**Describe the solution you'd like**
If `metadata.version` in zarf.yaml has a value, I'd like that value to appear in the package filename when it is created.

**Describe alternatives you've considered**
I could rename the package after it is created, but it would be nice if that happened for me.

**Additional context**
Since updating values inside files is a pain when using automation, I think it would also be great if we had a cli flag to set the version of the package on create. Something like `zarf package create --version 1.2.3 --confirm` which would result in a file named `zarf-package-foo-1.2.3-amd64.tar.zst`

**Comment by jeff-mccoy** [comment]
Okay so to understand the proposal is only for the (optional) metadata version to reflect in the package filename? Some more questions:

- What would happen if this optional field is not specified? 
- Is it odd to have a different naming convention for init vs normal zarf packages? We use `zarf-init-<arch>-<version>.tar.zst` for init packages. 
- What would happen if the init package has both a CLI version and metadata version?

**Comment by jeff-mccoy** [comment]
I don't love the idea of making this the default behavior for all packages as it will really make automation/gitops messier (where the file may stay the same but versioning is done by the registry or git server).  Also we already can do package variables to set the metadata version, maybe it makes more sense to extend that to the package name as a suffix instead?

**Comment by jeff-mccoy** [comment]
If we didn't change any code fight now, someone could easily have automation to:

`zarf package create --set INSERVARHERE=1.0.0` and then `mv zarf-package-<somename>-<arch>.tar.zst whateveryouwant.tar.zst`

The name for the package only matters for finding it in the list when you don't specify a package during `zarf package inspect/deploy`. Only the file extension matters to zarf, and that's just to tell Archiver how to extract it.

**Comment by RothAndrew** [comment]
> What would happen if this optional field is not specified?

omit it from the filename?

> Is it odd to have a different naming convention for init vs normal zarf packages? We use zarf-init-<arch>-<version>.tar.zst for init 

I have no issues with using same format as init package

> What would happen if the init package has both a CLI version and metadata version?

not sure what you mean. I’m only concerned with deploy packages for this feature request

> I don't love the idea of making this the default behavior for all packages as it will really make automation/gitops messier (where the file may stay the same but versioning is done by the registry or git server). Also we already can do package variables to set the metadata version, maybe it makes more sense to extend that to the package name as a suffix instead?

IMO default behavior is not setting the optional version field, which could preserve the existing filename format. If another mechanism is handling version control like a registry, setting the version field is likely not necessary

> If we didn't change any code right now, someone could easily have automation to…

See “alternatives considered” section

**Comment by Racer159** [comment]
That is actually how it is implemented as well (should have made that note).  The PR will

1. Omit the version if it is not set
2. Match the init package format with version after arch

Also
3. Currently this is very unlikely due to the tight coupling of the Zarf CLI and its Agent - the init package version effectively has to match the CLI version (and I can update the PR to add automation around this since we don't add the init package version to metadata right now)
4. We could easily add a `-o` or `--output` flag like curl has to manually set a desired filename

**Comment by jeff-mccoy** [comment]
Thinking about this some more, almost no one uses the `metatadata.version` field right now (including us), having that happen automatically if you happen to use that field is probably reasonable. I don't personally love this idea, but since we do expose the version field in the package I understand it's not totally unreasonable to provide this functionality as well.  My main ask would be that we keep the primary examples / packages throughout without this field. I also really like the idea of adding the `--output` options as well.
