### ISSUE TITLE
💡 Integration beween Zarf and Grype for Vulnerability scans

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#990]
**Is your feature request related to a problem? Please describe.**

Look into Integration between Zarf and Grype - to make the flow from generating an SBOM to checking for known vulnerabilities more seamless. 

Use case from current user: persona is package creator
> Create zarf package to generate SBOM
> inspect zarf package
> export SBOM file and import into Dependency track to track dependencies and ensure no known vulnerabilities 
> Open to using another tool (Grype might be easiest since we use syft under the hood)

**Describe the solution you'd like**

As a package creator - when I inspect a zarf package, I would like the option to connect to Grype and run a vulnerability scan for any known vulnerabilities. 

Desired outcomes - Provide high level of confidence that there are no known vulnerabilities in zarf package before it is sent to airgap environments. 

**Describe alternatives you've considered**
Zarf could also provide an option to export or share SBOM file with other OS tools like dependency tracks
Interested in how a package deployer on the airgap side would want to consume this information
Is there a need to certify how many known vulnerabilities a package has before deployment (current SBOM UI does not provide this information)?

**Comment by RothAndrew** [comment]
> Desired outcomes - prove that there are no known vulnerabilities in zarf package before it is sent to airgap environments.

Nit: "prove" may not be the best word to use. Having a grype report will be really good but grype won't necessarily find everything there is to find. Most robust security pipelines will use 2 or more tools like grype since each one tends to come up with different results.

Here's a good article on the phenomenon that was written a few years ago. It's a little long in the tooth now but there was an update posted and there are others that can be found via a quick google search: https://kubedex.com/container-scanning/

**Comment by Madeline-UX** [comment]
@jeff-mccoy  Im good with avoiding the "prove" wording. That came directly from a user. Based on your definition of this flow, it sounds like "confidence variable" would better communicate the desired concept.

**Comment by Noxsios** [comment]
`zarf package inspect --sbom-out <dir>` will spit out a package's SBOMs. The SBOM JSON files can then be ingested by w/e system needs them, and can be converted w/  `zarf tools sbom convert`.
